### ISSUE TITLE
incomplete

### ISSUE THREAD

**Issue by ramanaditya** [rafi007akhtar/CentralBank#1]
The templates are missing

**Comment by rafi007akhtar** [comment]
For which app? Be a little more specific, please.

**Comment by ramanaditya** [comment]
Like only two pages(html) are there and when you click on the link like create your account or log in it throws templates not found error it gives error as

**Comment by rafi007akhtar** [comment]
# Fixed the bug!
Please try now and let me know if it works for you.

## The bug
I wrote this web-app in Windows, and the URL rendering in views of Windows does not work with Linux. On the other hand, the URL rendering of Linux works in both operating systems.

More precisely, ` "accounts\create_account.html"` is valid in only Windows, but `"accounts/create_account.html"` is valid for both Windows and Linux. This Django project was written with the Windows naming system, and hence the error in Linux operating systems.

## The remedy
Accordingly, I changed all the rendering paths from `A\B` to `A/B` in the views of apps `accounts` and `profiles`. Now the templates load in all operating systems.

You can run `git diff` to see the changes in details, or go through the commit history if you wish to.

## Thank you
For pointing out the bug. Let me know if the changes work for you. If they don't, specify the bug in a separate Issue. For now, I am closing this issue.
